version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn add @babel/plugin-proposal-private-methods @babel/plugin-proposal-private-property-in-object && rails db:migrate && rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"